### ISSUE TITLE
Not able to execute fastxml.py file .

### ISSUE THREAD

**Issue by purviprajapati196** [Refefer/fastxml#10]
I did all the requirements.
numpy>=1.8.1
scipy>=0.13.3
scikit-learn>=0.17
Cython>=0.23.4
future>=0.16.0

after that i downloaded deliciousLarge dataset from Extreme Classification Repository.
I saved this dataset in fastxml_master folder.

I tried following command : 
fxml.py delicious.model deliciousLarge_train.txt --standard-dataset --verbose train --iters 5 --trees 20 --label-weight propensity --alpha 1e-4 --leaf-classifiers --no-remap-labels

I got Syntax error. at delicious.model. 
what is model file?

**Comment by Refefer** [comment]
Fxml.py is actually a command line application.  It appears you tried to
run that  from within a python shell instead of from the command line.

**Comment by purviprajapati196** [comment]
Still I am getting syntax error on command prompt...
kindly tell me what is model file....and i tried following command ...is it write?

fxml.py delicious.model deliciousLarge_train.txt --standard-dataset --verbose train --iters 5 --trees 20 --label-weight propensity --alpha 1e-4 --leaf-classifiers --no-remap-labels

**Comment by purviprajapati196** [comment]
kindly check the error ....
fxml.py is not able to search fastXML folder...
[New Microsoft Word Document (2).docx](https://github.com/Refefer/fastxml/files/1907335/New.Microsoft.Word.Document.2.docx)

**Comment by purviprajapati196** [comment]
Traceback (most recent call last):
  File "fxml.py", line 27, in <module>
    from fastxml import Inferencer, Trainer, metric_cluster
  File "C:\Users\admin\Desktop\fastxml-master\fastxml-master\bin\fastxml\__init_
_.py", line 1, in <module>
    from .fastxml import Inferencer
  File "C:\Users\admin\Desktop\fastxml-master\fastxml-master\bin\fastxml\fastxml
.py", line 9, in <module>
    from .inferencer import IForest, LeafComputer, Blender, IForestBlender
ModuleNotFoundError: No module named 'fastxml.inferencer'

**Comment by Refefer** [comment]
It's looking like you didn't install fastxml correctly, if at all.  I also don't know what fastxml_init_.py is - that file doesn't exist in the repo.

Did you `pip install fastxml`?  Since it looks like you have checked out the code as well, I would suggest you run `python setup.py develop` to actually install the binary.

Looking at the screenshot above, you're trying to run the command using `python fxml.py ...` which is redundant since the setup.py script should add fxml.py to your path.

**Comment by purviprajapati196** [comment]
Thanks for the reply.............
 Sir I tried according to your suggestions.... Now i got errors in splitter.cpp ... ididnt understand it...kindly check the attached document.

[fxml_error.docx](https://github.com/Refefer/fastxml/files/1910121/fxml_error.docx)

**Comment by purviprajapati196** [comment]
Sir,

Kindly check my attached document...

I am not able to solve it...
kindly help me.

**Comment by Refefer** [comment]
The error produced is pretty clear - you don't have a c++11 compiler on your machine.  You need it to be able to compile the Cython code.

**Comment by purviprajapati196** [comment]
sir 
I have installed TDM-GCC-64 for C++11 compiler. still i am getting error.

**Comment by purviprajapati196** [comment]
Kindly check my errors in attached file. 
[error.docx](https://github.com/Refefer/fastxml/files/2008373/error.docx)
