### ISSUE TITLE
ModuleNotFoundError: No module named 'fastxml.inferencer'

### ISSUE THREAD

**Issue by mattesko** [Refefer/fastxml#22]
I've installed the module's requirements with `conda install --file requirements.txt` and have run the setup with `python setup.py install` without any issues (apart from the deprecation warnings I see when I run the setup)

However, when I attempt to import the module, I get the following error:
Traceback (most recent call last):
  File "\<string\>", line 1, in \<module\>
  File "/home/leskokm/fastxml/fastxml/\_\_init\_\_.py", line 1, in \<module\>
    from .fastxml import Inferencer
  File "/home/leskokm/fastxml/fastxml/fastxml.py", line 9, in \<module\>
    from .inferencer import IForest, LeafComputer, Blender, IForestBlender
ModuleNotFoundError: No module named 'fastxml.inferencer'

Could there be an issue with the setup.py?

**Comment by Refefer** [comment]
Sounds like a path/install location problem.  Are you using a virtualenv?
I don't use conda so I'm not sure if that's a factor in the install.

You could try a python setup.py develop and see if the same behavior
persists.  Which version of python are you using?

**Comment by mattesko** [comment]
Thanks for getting back to me on this!
I'm using:
- anaconda3 virtualenv == 4.7.5
- python 64-bit == 3.7.3

I'll try out python setup.py develop

**Comment by mattesko** [comment]
I ran python setup.py develop and the issue is gone! I believe this issue can be marked as resolved.
Thank you!
